### ISSUE TITLE
Web page is not well centered when on mobile

### ISSUE THREAD

**Issue by lekandev** [lekandev/Pokedex-app#1]
The web page that shows when the live site is visited is not well positioned at the center but rather pushes itself to the right
It uses css grid

**Comment by rllyhz** [comment]
After i took a look, it seem you set the value of property `grid-template-columns` to `minmax(320px, 1fr)`, like these:

```css
#pokedex {
   grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
}
```

which is good... 
but, it always maintains the width of each **card item** in the parent (in case `#pokedox` ol element) at least `320px` on all the sizes of the screen (viewport), even it's on the smallest size.
so when it's on a smaller screen (smaller than the width of all card items), the **card items** will exceed the parent width...

for a brief solution, you can use media queries to define different behaviors on the different viewports.

**Comment by lekandev** [comment]
Oh okay I get what you mean, I didn't know that was the cause, do you think something like this with media queries as you suggested would work, thanks for your help

`@media only screen and (min-device-width: 320px) and (max-device-width: 480px) { 
        ​#​pokedex​ {
   ​              grid-template-columns: ​repeat (auto-fit​,​ ​minmax​(​220px,​ ​1​fr​));
}
}
`

**Comment by rllyhz** [comment]
Yeahh, it will work..

**Comment by lekandev** [comment]
it didnt work...

**Comment by rllyhz** [comment]
Its because you used min-device-width instead of min-width.. 

Since min-device-width and max-device-width have been deprecated according to this [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width), just use min-width or max-width instead..


I think it's going to work that way..

**Comment by lekandev** [comment]
I never used max-device-width in the CSS

But I think I'm going to adjust something with media queries
Thanks for your help
The problem is in my minmax values and padding

**Comment by godwin-morwin** [comment]
@lekandev have you figured it out yet?

**Comment by lekandev** [comment]
not yet @Godwindaniel10 
still having issues

**Comment by godwin-morwin** [comment]
@lekandev can you describe what and what the issue is all about, maybe I can help .

**Comment by lekandev** [comment]
it is not well centered on mobile devices, it sort of shifts to the right

**Comment by lekandev** [comment]
But wait @leshawn-rice submitted a pull request and he has fixed it, thank you for wanting to help. 😁🙏

**Comment by lekandev** [comment]
https://lekanpokedex-git-fork-leshawn-rice-window-sizing-lekandev.vercel.app/
